name: acr-1
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-acr
      - manual-trigger-acr-1
  schedule:
    - cron: '0 6 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@main
        env:
          OCI_ROOT_URL: https://acroci.azurecr.io
          OCI_NAMESPACE: ocitest/pull
          OCI_USERNAME: ${{ secrets.ACR_USERNAME }}
          OCI_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          OCI_TEST_PULL: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
      - name: Upload test report to S3
        run: aws s3 cp --region=us-east-1 --acl public-read report.html s3://oci-conformance/distribution-spec/acr/pull/report.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_AWS_SECRET_ACCESS_KEY }}
