name: trow-4
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-trow
      - manual-trigger-trow-4
  schedule:
    - cron: '50 6 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out trow
        uses: actions/checkout@v2
        with:
          path: trow
          repository: ContainerSolutions/trow
      - name: Start trow server
        run: |
          cd ./trow
          IP="$(hostname -I | awk '{print $1}')"
          echo "::set-env name=OCI_ROOT_URL::http://${IP}:8000"
          TROW_REF="local-trow:v$(date +%Y%m%d%H%M%S)"
          docker build -f docker/Dockerfile -t "${TROW_REF}" .
          docker run --rm -d -p 8000:8000 "${TROW_REF}" --no-tls
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@main
        env:
          OCI_ROOT_URL: ${{ env.OCI_ROOT_URL }}
          OCI_NAMESPACE: oci-conformance/distribution-test
          OCI_TEST_CONTENT_MANAGEMENT: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
      - name: Upload test report to S3
        run: aws s3 cp --region=us-east-1 --acl public-read report.html s3://oci-conformance/distribution-spec/trow/content-management/report.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_AWS_SECRET_ACCESS_KEY }}
