name: zot-2
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-zot
      - manual-trigger-zot-2
  schedule:
    - cron: '0 7 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: setup docker
        uses: docker-practice/actions-setup-docker@0.0.1
        with:
          docker_version: 18.09
          docker_channel: stable
      - name: checkout this repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: checkout zot
        uses: actions/checkout@v2
        with:
          path: zot
          repository: anuvu/zot
      - name: start zot server
        run: |
          mv main/.github/config/zot-config.yml ./zot
          cd ./zot
          IP=`hostname -I | awk '{print $1}'`
          echo "name=OCI_ROOT_URL::http://${IP}:5000" >> $GITHUB_ENV
          ZOT_REF="local-zot:v$(date +%Y%m%d%H%M%S)"
          docker build -t "${ZOT_REF}" .
          docker run --rm -p 5000:5000 -v "$(pwd)/zot-config.yml":/etc/zot/config.yml -idt "${ZOT_REF}"
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@main
        env:
          OCI_ROOT_URL: ${{ env.OCI_ROOT_URL }}
          OCI_NAMESPACE: oci-conformance/distribution-test
          OCI_TEST_PUSH: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
      - name: Upload test report to S3
        run: aws s3 cp --region=us-east-1 --acl public-read report.html s3://oci-conformance/distribution-spec/zot/push/report.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_AWS_SECRET_ACCESS_KEY }}
